// TODO: make this a string enum so that all the aria-labels work right with screen readers

export enum Field {
  // action:
  AC_NAME,
  AC_TYPE,
  AC_ROLE_KEY,
  AC_SAVE,
  AC_DELETE,
  AC_DELETE_MODAL_DELETE,
  AC_DELETE_MODAL_CANCEL,
  // action: bring app : app path
  AC_BRING_PATH_RADIO,
  AC_BRING_PATH_VALUE,
  AC_BRING_PATH_VAR,
  // action: bring app : app title
  AC_BRING_TITLE_RADIO,
  AC_BRING_TITLE_VALUE,
  AC_BRING_TITLE_VAR,
  // action: bring app : start dir
  AC_BRING_START_DIR_RADIO,
  AC_BRING_START_DIR_VALUE,
  AC_BRING_START_DIR_VAR,
  // action: call function : parameter
  AC_CALL_FUNC_FN,
  AC_CALL_FUNC_PARAMETER_RADIO,
  AC_CALL_FUNC_PARAMETER_VALUE,
  AC_CALL_FUNC_PARAMETER_VAR,
  // action: pause
  AC_SECONDS_RADIO,
  AC_SECONDS_VALUE,
  AC_SECONDS_VAR,
  // action: mimic : words
  AC_MIMIC_WORDS_RADIO,
  AC_MIMIC_WORDS_VALUE,
  AC_MIMIC_WORDS_VAR,
  // action: mouse
  AC_MOUSE_ACTION_TYPE,
  // action: mouse : move
  AC_MOUSE_MOVEMENT_TYPE,
  // action: mouse : move : x
  AC_MOUSE_X_RADIO,
  AC_MOUSE_X_VALUE,
  AC_MOUSE_X_VAR,
  // action: mouse : move : y
  AC_MOUSE_Y_RADIO,
  AC_MOUSE_Y_VALUE,
  AC_MOUSE_Y_VAR,
  // action: mouse : click
  AC_MOUSE_MOUSE_BUTTON_RADIO,
  AC_MOUSE_MOUSE_BUTTON_VALUE,
  AC_MOUSE_MOUSE_BUTTON_VAR,
  // action: mouse : click/hold
  AC_MOUSE_PAUSE_RADIO,
  AC_MOUSE_PAUSE_VALUE,
  AC_MOUSE_PAUSE_VAR,
  // action: mouse : repeat
  AC_MOUSE_REPEAT_RADIO,
  AC_MOUSE_REPEAT_VALUE,
  AC_MOUSE_REPEAT_VAR,
  // action: mouse : direction
  AC_MOUSE_DIRECTION_RADIO,
  AC_MOUSE_DIRECTION_VALUE,
  AC_MOUSE_DIRECTION_VAR,
  // action: send key :
  AC_SEND_KEY_MODE,
  // action: send key : direction
  AC_SK_DIRECTION_RADIO,
  AC_SK_DIRECTION_VALUE,
  AC_SK_DIRECTION_VAR,
  // action: send key : inner pause
  AC_SK_INNER_PAUSE_RADIO,
  AC_SK_INNER_PAUSE_VALUE,
  AC_SK_INNER_PAUSE_VAR,
  // action: send key : key to send
  AC_SK_KEY_TO_SEND_RADIO,
  AC_SK_KEY_TO_SEND_VALUE,
  AC_SK_KEY_TO_SEND_VAR,
  // action: send key : outer pause
  AC_SK_OUTER_PAUSE_RADIO,
  AC_SK_OUTER_PAUSE_VALUE,
  AC_SK_OUTER_PAUSE_VAR,
  // action: send key : repeat
  AC_SK_REPEAT_RADIO,
  AC_SK_REPEAT_VALUE,
  AC_SK_REPEAT_VAR,
  // action: send text : text
  AC_ST_TEXT_RADIO,
  AC_ST_TEXT_VALUE,
  AC_ST_TEXT_VAR,
  // action: wait for window : executable
  AC_WFW_EXECUTABLE_RADIO,
  AC_WFW_EXECUTABLE_VALUE,
  AC_WFW_EXECUTABLE_VAR,
  // action: wait for window : title
  AC_WFW_TITLE_RADIO,
  AC_WFW_TITLE_VALUE,
  AC_WFW_TITLE_VAR,
  // action: wait for window : wait seconds
  AC_WFW_WAIT_SECONDS_RADIO,
  AC_WFW_WAIT_SECONDS_VALUE,
  AC_WFW_WAIT_SECONDS_VAR,
  // command:
  CMD_NAME,
  CMD_ROLE_KEY,
  CMD_CONTEXT,
  CMD_DELETE_MODAL_DELETE,
  CMD_DELETE_MODAL_CANCEL,
  // command: spec
  CMD_SPEC_SELECT,
  CMD_ACTION_SELECT,
  CMD_ACTION_DELETE,
  CMD_SAVE,
  CMD_DELETE,
  // context:
  CTX_MATCHER,
  CTX_NAME,
  CTX_ROLE_KEY,
  CTX_TYPE,
  CTX_DELETE,
  CTX_DELETE_MODAL_DELETE,
  CTX_DELETE_MODAL_CANCEL,
  // fn:
  FN_NAME,
  FN_ROLE_KEY,
  FN_TYPE,
  FN_IMPORT_PATH,
  FN_PARAMETER_NAME,
  FN_PARAMETER_TYPE,
  FN_PARAMETERS,
  FN_ADD_NEW_PARAMETER,
  FN_MOVE_PARAMETER,
  FN_DELETE_PARAMETER,
  FN_DELETE,
  FN_DELETE_MODAL_DELETE,
  FN_DELETE_MODAL_CANCEL,
  // preferences:
  PREFS_NEGATIVIZER,
  PREFS_THEME,
  // spec:
  SP_NAME,
  SP_ROLE_KEY,
  SP_ADD_ITEM_BUTTON,
  SP_ITEM_TYPE_SELECT,
  SP_ITEM_SELECTOR,
  SP_ITEM_VARIABLE,
  SP_ITEM_DELETE,
  SP_TOGGLE_SPEC_ITEM_OPTIONAL,
  SP_SAVE,
  SP_DELETE,
  SP_DELETE_MODAL_DELETE,
  SP_DELETE_MODAL_CANCEL,
  // variable:
  VAR_NAME,
  VAR_ROLE_KEY,
  VAR_TYPE_SELECT,
  VAR_USE_DEFAULT,
  VAR_TEXT_DEFAULT_VALUE,
  VAR_RANGE_MIN,
  VAR_RANGE_MAX,
  VAR_RANGE_DEFAULT_VALUE,
  VAR_CHOICE_ITEM_SELECTOR,
  VAR_CHOICE_DEFAULT_VALUE,
  VAR_ADD_ITEM_BUTTON,
  VAR_DELETE,
  VAR_DELETE_MODAL_DELETE,
  VAR_DELETE_MODAL_CANCEL,
  // wizards:
  WIZ_MC_CONTEXT,
  WIZ_MC_BTN,
  WIZ_MC_SPEC,
  WIZ_SK_CONTEXT,
  WIZ_SK_KEY,
  WIZ_SK_SPEC,
  WIZ_ST_CONTEXT,
  WIZ_ST_TEXT,
  WIZ_ST_SPEC,
}
