// put an enum-like here
export enum ValidationErrorCode {
  AC_KTS_EMPTY,
  AC_KTS_VAR_NOT_SELECTED,
  AC_KTS_RK_NOT_SELECTED,
  AC_OP_VAR_NOT_SELECTED,
  AC_OP_RK_NOT_SELECTED,
  AC_IP_VAR_NOT_SELECTED,
  AC_IP_RK_NOT_SELECTED,
  AC_RPT_VAR_NOT_SELECTED,
  AC_RPT_RK_NOT_SELECTED,
  AC_DIR_EMPTY,
  AC_DIR_VAR_NOT_SELECTED,
  AC_DIR_RK_NOT_SELECTED,
  CMD_SPEC_VAR_NOT_SELECTED,
  CMD_SPEC_RK_NOT_SELECTED,
  CTX_MATCHER_EMPTY,
  RK_EMPTY,

  SPEC_EMPTY_SELECTOR,
  SPEC_GTE1_SPEC_ITEM,
}
