// TODO: make this a string enum so that all the aria-labels work right with screen readers

export enum Field {
  // action:
  AC_NAME,
  AC_TYPE,
  AC_ROLE_KEY,
  AC_SAVE,
  AC_DELETE,
  AC_DELETE_MODAL_DELETE,
  AC_DELETE_MODAL_CANCEL,
  // action: pause
  AC_CENTISECONDS_RADIO,
  AC_CENTISECONDS_VALUE,
  AC_CENTISECONDS_VAR,
  // action: send key :
  AC_SEND_KEY_MODE,
  // action: mouse
  AC_MOUSE_ACTION_TYPE,
  AC_MOUSE_MOVEMENT_TYPE,
  AC_MOUSE_X,
  AC_MOUSE_Y,
  AC_MOUSE_MOUSE_BUTTON_RADIO,
  AC_MOUSE_MOUSE_BUTTON_VALUE,
  AC_MOUSE_MOUSE_BUTTON_VAR,
  //
  AC_MOUSE_PAUSE_RADIO,
  AC_MOUSE_PAUSE_VALUE,
  AC_MOUSE_PAUSE_VAR,
  //
  AC_MOUSE_REPEAT_RADIO,
  AC_MOUSE_REPEAT_VALUE,
  AC_MOUSE_REPEAT_VAR,
  //
  AC_MOUSE_DIRECTION_RADIO,
  AC_MOUSE_DIRECTION_VALUE,
  AC_MOUSE_DIRECTION_VAR,
  // action: send key : direction
  AC_SK_DIRECTION_RADIO,
  AC_SK_DIRECTION_VALUE,
  AC_SK_DIRECTION_VAR,
  // action: send key : inner pause
  AC_SK_INNER_PAUSE_RADIO,
  AC_SK_INNER_PAUSE_VALUE,
  AC_SK_INNER_PAUSE_VAR,
  // action: send key : key to send
  AC_SK_KEY_TO_SEND_RADIO,
  AC_SK_KEY_TO_SEND_VALUE,
  AC_SK_KEY_TO_SEND_VAR,
  // action: send key : outer pause
  AC_SK_OUTER_PAUSE_RADIO,
  AC_SK_OUTER_PAUSE_VALUE,
  AC_SK_OUTER_PAUSE_VAR,
  // action: send key : repeat
  AC_SK_REPEAT_RADIO,
  AC_SK_REPEAT_VALUE,
  AC_SK_REPEAT_VAR,
  // command:
  CMD_NAME,
  CMD_ROLE_KEY,
  CMD_CONTEXT,
  CMD_DELETE_MODAL_DELETE,
  CMD_DELETE_MODAL_CANCEL,
  // command: spec
  CMD_SPEC_SELECT,
  CMD_ACTION_SELECT,
  CMD_ACTION_DELETE,
  CMD_SAVE,
  CMD_DELETE,
  // context:
  CTX_MATCHER,
  CTX_NAME,
  CTX_ROLE_KEY,
  CTX_TYPE,
  CTX_DELETE,
  CTX_DELETE_MODAL_DELETE,
  CTX_DELETE_MODAL_CANCEL,
  // spec:
  SP_NAME,
  SP_ROLE_KEY,
  SP_ADD_ITEM_BUTTON,
  SP_ITEM_TYPE_SELECT,
  SP_ITEM_SELECTOR,
  SP_ITEM_VARIABLE,
  SP_ITEM_DELETE,
  SP_TOGGLE_SPEC_ITEM_OPTIONAL,
  SP_SAVE,
  SP_DELETE,
  SP_DELETE_MODAL_DELETE,
  SP_DELETE_MODAL_CANCEL,
  // variable:
  VAR_NAME,
  VAR_ROLE_KEY,
  VAR_TYPE_SELECT,
  VAR_USE_DEFAULT,
  VAR_TEXT_DEFAULT_VALUE,
  VAR_RANGE_MIN,
  VAR_RANGE_MAX,
  VAR_RANGE_DEFAULT_VALUE,
  VAR_CHOICE_ITEM_SELECTOR,
  VAR_CHOICE_DEFAULT_VALUE,
  VAR_ADD_ITEM_BUTTON,
  VAR_DELETE,
  VAR_DELETE_MODAL_DELETE,
  VAR_DELETE_MODAL_CANCEL,
}
