export namespace Key {
  export const Enum = {
    ALPHA: 'a (alpha)',
    BRAVO: 'b (bravo)',
    CHARLIE: 'c (charlie)',
    DELTA: 'd (delta)',
    ECHO: 'e (echo)',
    FOXTROT: 'f (foxtrot)',
    GOLF: 'g (golf)',
    HOTEL: 'h (hotel)',
    INDIA: 'i (india)',
    JULIET: 'j (juliet)',
    KILO: 'k (kilo)',
    LIMA: 'l (lima)',
    MIKE: 'm (mike)',
    NOVEMBER: 'n (november)',
    OSCAR: 'o (oscar)',
    PAPA: 'p (papa)',
    QUEBEC: 'q (quebec)',
    ROMEO: 'r (romeo)',
    SIERRA: 's (sierra)',
    TANGO: 't (tango)',
    UNIFORM: 'u (uniform)',
    VICTOR: 'v (victor)',
    WHISKY: 'w (whisky)',
    XRAY: 'x (xray)',
    YANKEE: 'y (yankee)',
    ZULU: 'z (zulu)',
    ZERO: '0 (zero)',
    ONE: '1 (one)',
    TWO: '2 (two)',
    THREE: '3 (three)',
    FOUR: '4 (four)',
    FIVE: '5 (five)',
    SIX: '6 (six)',
    SEVEN: '7 (seven)',
    EIGHT: '8 (eight)',
    NINE: '9 (nine)',
    EXCLAMATION: '! (exclamation)',
    AT: '@ (at)',
    HASH: '# (hash)',
    DOLLAR: '$ (dollar)',
    PERCENT: '% (percent)',
    CARET: '^ (caret)',
    AMPERSAND: '& (ampersand)',
    ASTERISK: '* (asterisk)',
    LEFTPAREN: '( (leftparen)',
    RIGHTPAREN: ') (rightparen)',
    HYPHEN: '- (hyphen)',
    UNDERSCORE: '_ (underscore)',
    PLUS: '+ (plus)',
    BACKTICK: '` (backtick)',
    TILDE: '~ (tilde)',
    LEFTBRACKET: '[ (leftbracket)',
    RIGHTBRACKET: '] (rightbracket)',
    LEFTBRACE: '{ (leftbrace)',
    RIGHTBRACE: '} (rightbrace)',
    BACKSLASH: '\\ (backslash)',
    BAR: '| (bar)',
    COLON: ': (colon)',
    SEMICOLON: '; (semicolon)',
    SINGLEQUOTE: "' (singlequote)",
    DOUBLEQUOTE: '" (doublequote)',
    COMMA: ', (comma)',
    DOT: '. (dot)',
    SLASH: '/ (slash)',
    LEFTANGLE: '< (leftangle)',
    RIGHTANGLE: '> (rightangle)',
    QUESTION: '? (question)',
    EQUAL: '= (equal)',
    ENTER: '(enter)',
    TAB: '(tab)',
    SPACE: '(space)',
    BACKSPACE: '(backspace)',
    DELETE: '(delete)',
    SHIFT: '(shift)',
    CONTROL: '(control)',
    ALT: '(alt)',
    RSHIFT: '(rshift)',
    RCONTROL: '(rcontrol)',
    RALT: '(ralt)',
    ESCAPE: '(escape)',
    INSERT: '(insert)',
    PAUSE: '(pause)',
    WIN: '(win)',
    RWIN: '(rwin)',
    APPS: '(apps)',
    PRINTSCREEN: '(printscreen)',
    SCROLLLOCK: '(scrolllock)',
    NUMLOCK: '(numlock)',
    CAPSLOCK: '(capslock)',
    UP: '(up)',
    DOWN: '(down)',
    LEFT: '(left)',
    RIGHT: '(right)',
    PAGEUP: '(pageup)',
    PAGEDOWN: '(pagedown)',
    HOME: '(home)',
    END: '(end)',
    NPMUL: '(npmul)',
    NPADD: '(npadd)',
    NPSEP: '(npsep)',
    NPSUB: '(npsub)',
    NPDEC: '(npdec)',
    NPDIV: '(npdiv)',
    NUMPAD0: '(numpad0)',
    NUMPAD1: '(numpad1)',
    NUMPAD2: '(numpad2)',
    NUMPAD3: '(numpad3)',
    NUMPAD4: '(numpad4)',
    NUMPAD5: '(numpad5)',
    NUMPAD6: '(numpad6)',
    NUMPAD7: '(numpad7)',
    NUMPAD8: '(numpad8)',
    NUMPAD9: '(numpad9)',
    F1: '(f1)',
    F2: '(f2)',
    F3: '(f3)',
    F4: '(f4)',
    F5: '(f5)',
    F6: '(f6)',
    F7: '(f7)',
    F8: '(f8)',
    F9: '(f9)',
    F10: '(f10)',
    F11: '(f11)',
    F12: '(f12)',
    F13: '(f13)',
    F14: '(f14)',
    F15: '(f15)',
    F16: '(f16)',
    F17: '(f17)',
    F18: '(f18)',
    F19: '(f19)',
    F20: '(f20)',
    F21: '(f21)',
    F22: '(f22)',
    F23: '(f23)',
    F24: '(f24)',
    VOLUMEUP: '(volumeup)',
    VOLUMEDOWN: '(volumedown)',
    VOLUMEMUTE: '(volumemute)',
    TRACKNEXT: '(tracknext)',
    TRACKPREV: '(trackprev)',
    PLAYPAUSE: '(playpause)',
    BROWSERBACK: '(browserback)',
    BROWSERFORWARD: '(browserforward)',
  } as const;
  export const values = () => [
    Enum.ALPHA,
    Enum.BRAVO,
    Enum.CHARLIE,
    Enum.DELTA,
    Enum.ECHO,
    Enum.FOXTROT,
    Enum.GOLF,
    Enum.HOTEL,
    Enum.INDIA,
    Enum.JULIET,
    Enum.KILO,
    Enum.LIMA,
    Enum.MIKE,
    Enum.NOVEMBER,
    Enum.OSCAR,
    Enum.PAPA,
    Enum.QUEBEC,
    Enum.ROMEO,
    Enum.SIERRA,
    Enum.TANGO,
    Enum.UNIFORM,
    Enum.VICTOR,
    Enum.WHISKY,
    Enum.XRAY,
    Enum.YANKEE,
    Enum.ZULU,
    Enum.ZERO,
    Enum.ONE,
    Enum.TWO,
    Enum.THREE,
    Enum.FOUR,
    Enum.FIVE,
    Enum.SIX,
    Enum.SEVEN,
    Enum.EIGHT,
    Enum.NINE,
    Enum.EXCLAMATION,
    Enum.AT,
    Enum.HASH,
    Enum.DOLLAR,
    Enum.PERCENT,
    Enum.CARET,
    Enum.AMPERSAND,
    Enum.ASTERISK,
    Enum.LEFTPAREN,
    Enum.RIGHTPAREN,
    Enum.HYPHEN,
    Enum.UNDERSCORE,
    Enum.PLUS,
    Enum.BACKTICK,
    Enum.TILDE,
    Enum.LEFTBRACKET,
    Enum.RIGHTBRACKET,
    Enum.LEFTBRACE,
    Enum.RIGHTBRACE,
    Enum.BACKSLASH,
    Enum.BAR,
    Enum.COLON,
    Enum.SEMICOLON,
    Enum.SINGLEQUOTE,
    Enum.DOUBLEQUOTE,
    Enum.COMMA,
    Enum.DOT,
    Enum.SLASH,
    Enum.LEFTANGLE,
    Enum.RIGHTANGLE,
    Enum.QUESTION,
    Enum.EQUAL,
    Enum.ENTER,
    Enum.TAB,
    Enum.SPACE,
    Enum.BACKSPACE,
    Enum.DELETE,
    Enum.SHIFT,
    Enum.CONTROL,
    Enum.ALT,
    Enum.RSHIFT,
    Enum.RCONTROL,
    Enum.RALT,
    Enum.ESCAPE,
    Enum.INSERT,
    Enum.PAUSE,
    Enum.WIN,
    Enum.RWIN,
    Enum.APPS,
    Enum.PRINTSCREEN,
    Enum.SCROLLLOCK,
    Enum.NUMLOCK,
    Enum.CAPSLOCK,
    Enum.UP,
    Enum.DOWN,
    Enum.LEFT,
    Enum.RIGHT,
    Enum.PAGEUP,
    Enum.PAGEDOWN,
    Enum.HOME,
    Enum.END,
    Enum.NPMUL,
    Enum.NPADD,
    Enum.NPSEP,
    Enum.NPSUB,
    Enum.NPDEC,
    Enum.NPDIV,
    Enum.NUMPAD0,
    Enum.NUMPAD1,
    Enum.NUMPAD2,
    Enum.NUMPAD3,
    Enum.NUMPAD4,
    Enum.NUMPAD5,
    Enum.NUMPAD6,
    Enum.NUMPAD7,
    Enum.NUMPAD8,
    Enum.NUMPAD9,
    Enum.F1,
    Enum.F2,
    Enum.F3,
    Enum.F4,
    Enum.F5,
    Enum.F6,
    Enum.F7,
    Enum.F8,
    Enum.F9,
    Enum.F10,
    Enum.F11,
    Enum.F12,
    Enum.F13,
    Enum.F14,
    Enum.F15,
    Enum.F16,
    Enum.F17,
    Enum.F18,
    Enum.F19,
    Enum.F20,
    Enum.F21,
    Enum.F22,
    Enum.F23,
    Enum.F24,
    Enum.VOLUMEUP,
    Enum.VOLUMEDOWN,
    Enum.VOLUMEMUTE,
    Enum.TRACKNEXT,
    Enum.TRACKPREV,
    Enum.PLAYPAUSE,
    Enum.BROWSERBACK,
    Enum.BROWSERFORWARD,
  ];
  export type Type = typeof Enum[keyof typeof Enum];
}
