export enum ErrorCode {
  SELECTOR_ID_NOT_FOUND,
  SELECTOR_ID_ALREADY_IN_USE,

  NOT_EDITING_AN_ACTION,

  UNHANDLED_ACTION_TYPE,
  UNHANDLED_ACTION_VALUE_TYPE,
  UNHANDLED_ACTION_VALUE_OPERATION,
  UNHANDLED_SEND_KEY_FIELD,
  UNHANDLED_SEND_KEY_MODE,
  UNHANDLED_SEND_KEY_MODIFIER_TYPE,
  UNHANDLED_SPEC_ITEM_TYPE,
  UNHANDLED_VARIABLE_TYPE,
}
